# Generated by Django 5.2.1 on 2025-05-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Station Manager'), ('delivery', 'Delivery Staff'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
